// Bundles the main service (src/) and its dependencies into <plugin>/plugin/app.js.
import path from 'node:path';
import { build } from 'esbuild';
import { isMain, PLUGIN_DIR, ROOT } from './lib/paths.mjs';

export async function buildPlugin() {
  await build({
    entryPoints: [path.join(ROOT, 'src', 'app.js')],
    outfile: path.join(PLUGIN_DIR, 'plugin', 'app.js'),
    bundle: true,
    platform: 'node',
    // Ulanzi Studio runs Node.js plugins with its bundled Node.js 20
    target: 'node20',
    // plugin/package.json declares "type": "commonjs"
    format: 'cjs',
    // optional native add-ons of ws; it falls back to plain JavaScript without them
    external: ['bufferutil', 'utf-8-validate'],
    banner: { js: '// Generated by scripts/build.mjs from src/ — do not edit.' },
    logLevel: 'warning',
  });
}

if (isMain(import.meta.url)) {
  await buildPlugin();
  console.log(`Built ${path.relative(ROOT, path.join(PLUGIN_DIR, 'plugin', 'app.js'))}`);
}
